version: 0.0
Resources: 
    - TargetService: 
        Type: AWS::ECS::Service
        Properties:
            TaskDefinition: "arn:aws:ecs:us-east-2:885193784904:task-definition/#{EnvironmentName}_#{TaskDefinitionFamily}"
            LoadBalancerInfo:
                ContainerName: "web-app-container"
                ContainerPort: 80
