version: 0.0
Resources: 
    - TargetService: 
        Type: AWS::ECS::Service
        Properties:
            TaskDefinition: "## task ARN ##"
            LoadBalancerInfo:
                ContainerName: "web-app-container"
                ContainerPort: 80
